{ config, lib, pkgs, host, ... }:

{
  # --- Boot ---
  boot.loader.systemd-boot.enable = lib.mkForce false;   # Lanzaboote replaces systemd-boot install
  boot.loader.systemd-boot.configurationLimit = 15;   # Each UKI is ~50-80MB, keep ESP usage under control
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.timeout = 30;   # 30s menu delay for dual-boot drive selection
  boot.lanzaboote = {
    enable = true;
    pkiBundle = "/var/lib/sbctl";   # Secure Boot signing keys (generated by sbctl create-keys)
  };
  boot.kernelPackages = pkgs.linuxPackages_latest;   # Latest kernel for newest hardware support
  boot.kernelParams = lib.mkIf host.nvidia [ "nvidia_drm.fbdev=1" ];   # NVIDIA framebuffer (Wayland)

  # tmpfs on RAM -- faster builds, reduces SSD writes
  boot.tmp.useTmpfs = true;
  boot.tmp.tmpfsSize = host.tmpfsSize;

  # --- Kernel hang / panic safety net ---
  # Escape hatch if a driver BUG() wedges the machine (e.g. mt7925e list_add corruption).
  # Without these a kernel BUG can silently deadlock every CPU waiting on orphaned locks.
  boot.kernel.sysctl = {
    "kernel.panic_on_oops" = 1;      # BUG()/oops => panic, don't try to limp on
    "kernel.panic" = 10;             # reboot 10s after panic
    "kernel.hardlockup_panic" = 1;   # CPU ignored IRQs >10s => panic via NMI
    "kernel.softlockup_panic" = 1;   # CPU looped in kernel >20s => panic
    "kernel.hung_task_panic" = 1;    # task stuck in D-state >120s => panic
  };
  # Hardware watchdog -- sp5100_tco on this AMD chipset. If systemd stops
  # pinging it, the chipset itself resets the box. Only option that survives
  # the scenario where every CPU is deadlocked and software watchdogs can't run.
  systemd.settings.Manager.RuntimeWatchdogSec = "30s";

  # AMD CPU microcode updates -- security and stability patches
  hardware.cpu.amd.updateMicrocode = true;

  # Btrfs -- reduces SSD writes (noatime) and saves space (zstd compression)
  fileSystems."/".options = [ "noatime" "compress=zstd" ];
  fileSystems."/home".options = [ "noatime" "compress=zstd" ];

  # --- GPU ---
  hardware.graphics = {
    enable = true;
    enable32Bit = true;   # Needed for Steam/Proton 32-bit games
  };
  services.xserver.videoDrivers = lib.mkIf host.nvidia [ "nvidia" ];
  hardware.nvidia = lib.mkIf host.nvidia {
    modesetting.enable = true;
    open = true;                       # Open kernel modules -- required for 50-series (Blackwell) and newer
    nvidiaSettings = true;             # nvidia-settings GUI
    package = config.boot.kernelPackages.nvidiaPackages.latest;
  };

  # Allow non-root users to read GPU performance counters (ncu, CUPTI PC sampling).
  # Default gates this behind root to mitigate CVE-2018-6260 (GPU counter side-channel
  # between users on a shared GPU); single-user workstation, threat model doesn't apply.
  boot.extraModprobeConfig = lib.mkIf host.nvidia ''
    options nvidia NVreg_RestrictProfilingToAdminUsers=0
  '';

  # VA-API hardware video acceleration via NVIDIA
  environment.variables.LIBVA_DRIVER_NAME = lib.mkIf host.nvidia "nvidia";

  # --- Hardware Services ---
  services.fstrim.enable = true;        # Weekly SSD TRIM -- maintains write performance and longevity
  services.smartd.enable = true;        # Monitor SSD/HDD health via SMART -- warns before failure
  services.irqbalance.enable = true;    # Distribute hardware interrupts across CPU cores

  # --- Bluetooth ---
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;
  services.blueman.enable = true;       # Bluetooth GUI manager

  # --- Swap ---
  zramSwap.enable = true;              # Compressed RAM swap -- OOM pressure relief without SSD wear

  # --- Sleep disabled ---
  # NVIDIA RTX 5090 + open driver hangs GSP on S3 resume:
  # Xid 13/31 cascade, then Xid 154 "Node Reboot Required". Mask all sleep
  # targets so no path (logind, hypridle, power button) can trigger suspend.
  systemd.targets.sleep.enable = false;
  systemd.targets.suspend.enable = false;
  systemd.targets.hibernate.enable = false;
  systemd.targets.hybrid-sleep.enable = false;
  services.logind.settings.Login = {
    HandleSuspendKey = "ignore";
    HandleHibernateKey = "ignore";
    HandleLidSwitch = "ignore";
    HandleLidSwitchExternalPower = "ignore";
    HandleLidSwitchDocked = "ignore";
    IdleAction = "ignore";
  };
}
